# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# Enable console over USB
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

# Use only the new USB device stack
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y

# ADD THESE SPI CONFIGURATIONS:
CONFIG_SPI=y
CONFIG_LORA=y
CONFIG_GPIO=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

# Use native SX126x driver
# CONFIG_LORA_MODULE_BACKEND_NONE=y  # This symbol is not available in current Zephyr
# Enable SX126x driver
CONFIG_LORA_SX126X=y

# Enable unique serial number from chip ID
CONFIG_HWINFO=y

# Optional: Logging levels for debugging
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG=n
# CONFIG_PRINTK=n
CONFIG_USBD_LOG_LEVEL_WRN=n
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=n
CONFIG_USBD_CDC_ACM_LOG_LEVEL_ERR=n


# Optional: USB product strings
CONFIG_SAMPLE_USBD_PID=0xBABB
CONFIG_SAMPLE_USBD_PRODUCT="Catsniffer"
CONFIG_SAMPLE_USBD_MANUFACTURER="Electronic Cats"

# (legacy USB stack )
# CONFIG_USB_DEVICE_STACK=y
# CONFIG_USB_DEVICE_PRODUCT="Zephyr CDC ACM sample"
# CONFIG_USB_DEVICE_PID=0x0001
# CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
# CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
# CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
