#!/usr/bin/env python3
"""Dump the full catnip command tree (every ``--help``) to stdout.

Reference snapshot used by the CLI refactor (see ``CLI_REFACTOR_PLAN.md``):
each phase must leave this output byte-for-byte identical.

    python scripts/dump_cli_tree.py > /tmp/tree.txt
    diff /tmp/tree.txt tests/snapshots/cli_tree_linux.txt

The output is platform dependent (``vhci``/``setup-env`` are Linux only,
``completion`` is Linux/macOS only), hence the platform in the header and in
the snapshot filename.
"""

import os
import sys
from pathlib import Path

# Stable help wrapping regardless of the invoking terminal.
os.environ["COLUMNS"] = "100"

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import click  # noqa: E402
from click.testing import CliRunner  # noqa: E402

from modules.core.cli import build_cli  # noqa: E402


def walk(command, path):
    """Yield ``(path, command)`` depth-first, groups before their children."""
    yield path, command
    if isinstance(command, click.Group):
        for name in command.list_commands(click.Context(command)):
            child = command.get_command(click.Context(command), name)
            if child is None:
                continue
            yield from walk(child, path + [name])


def main() -> int:
    root = build_cli()
    runner = CliRunner()

    print(f"# catnip CLI tree snapshot (platform: {sys.platform})")
    print("# generated by scripts/dump_cli_tree.py -- do not edit by hand")
    # On stderr so it never shows up in a diff of two snapshots.
    from importlib.metadata import version

    print(f"click {version('click')}", file=sys.stderr)

    for path, command in walk(root, ["catnip"]):
        label = " ".join(path)
        print()
        print("=" * 78)
        print(f"$ {label} --help")
        print("=" * 78)
        result = runner.invoke(
            root, path[1:] + ["--help"], prog_name="catnip", catch_exceptions=False
        )
        sys.stdout.write(result.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
