[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Show prints in console when running tests
addopts =
    -v
    --tb=short
    --strict-markers
    --no-header

# Custom markers for organizing tests
markers =
    unit: unit tests that are fast and do not require external dependencies
    integration: tests that require hardware or connection
    slow: test that takes a long time to run
